name: Deploy nsite
on:
  push:
    branches:
      - master

concurrency:
  group: "nsite"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Copy to pages
        run: pnpm pages

      - name: Deploy nsite
        run: npx -y nsite-cli upload pages --verbose --purge --privatekey ${{ secrets.NSITE_KEY }}
